---
version: "3"
services:
  maven:
    build:
      context: .
      dockerfile: Dockerfile.maven
    container_name: maven
    volumes:
      - web_data:/boxfuse/boxfuse-sample-java-war-hello/target/
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    container_name: tomcat
    volumes:
      - web_data:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"
    restart: on-failure:3
volumes:
  web_data:
